//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 2
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /workspace/clif_backend/llvm/llvm/tools/clif/python/utils/proto_util.clif

#include <Python.h>

namespace clif_python_utils_proto__util_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace clif_python_utils_proto__util_clifwrap

PyMODINIT_FUNC initproto_util(void) {
  clif_python_utils_proto__util_clifwrap::Ready() &&
  clif_python_utils_proto__util_clifwrap::Init();
}
